"""add_fecha_ultima_cotizacion_to_clientes

Revision ID: d507a4360132
Revises: 21f59b5ff705
Create Date: 2026-01-27 11:43:46.417941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd507a4360132'
down_revision: Union[str, None] = '21f59b5ff705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('fecha_ultima_cotizacion', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
